import 'package:flutter/material.dart';
import 'package:flutterapp/key_20genaratorapp/generatedappmobilewidget/generated/GeneratedFrame1Widget.dart';
import 'package:flutterapp/key_20genaratorapp/generatedappmobilewidget/generated/GeneratedCopybuttonWidget.dart';
import 'package:flutterapp/key_20genaratorapp/generatedappmobilewidget/generated/GeneratedButtonGenrateWidget.dart';
import 'package:flutterapp/key_20genaratorapp/generatedappmobilewidget/generated/GeneratedBlurfaceWidget.dart';
import 'package:flutterapp/key_20genaratorapp/generatedappmobilewidget/generated/GeneratedBack1Widget.dart';
import 'package:flutterapp/key_20genaratorapp/generatedappmobilewidget/generated/GeneratedInputfiledWidget.dart';

/* Frame App mobile
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAppmobileWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 17.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 909.0,
                              child: GeneratedBack1Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 926.0,
                              child: GeneratedBlurfaceWidget(),
                            ),
                            Positioned(
                              left: 22.0,
                              top: 647.0,
                              right: null,
                              bottom: null,
                              width: 387.0,
                              height: 205.0,
                              child: GeneratedFrame1Widget(),
                            ),
                            Positioned(
                              left: 22.0,
                              top: 128.0,
                              right: null,
                              bottom: null,
                              width: 285.0,
                              height: 60.0,
                              child: GeneratedInputfiledWidget(),
                            ),
                            Positioned(
                              left: 345.0,
                              top: 127.0,
                              right: null,
                              bottom: null,
                              width: 60.0,
                              height: 60.0,
                              child: GeneratedCopybuttonWidget(),
                            ),
                            Positioned(
                              left: 134.0,
                              top: 521.0,
                              right: null,
                              bottom: null,
                              width: 160.0,
                              height: 51.0,
                              child: GeneratedButtonGenrateWidget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
